language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-support-24.2.1

branches:
  only:
  - master

before-script:
  - chmod +x gradlew

install:
    - true

script:
  - TERM=dumb ./gradlew :infinity:assembleDebug -Dpre-dex=false

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
