language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24

branches:
  only:
  - master

before-script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window -gpu off -no-boot-anim &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
  
install:
    - true

script:
  - TERM=dumb ./gradlew :infinity:assembleDebug -Dpre-dex=false checkConnected

after_failure: 
  - cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
